FROM ubuntu:20.04

ARG hadoop_version='3.3.1'

RUN apt-get update \
  && apt-get install -y openjdk-8-jdk sudo ssh wget nano vim

RUN useradd -ms /bin/bash hadoop && echo "hadoop:supergroup" | chpasswd && adduser hadoop sudo && echo "hadoop     ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && cd /usr/bin/ && sudo ln -s python3 python

RUN mkdir -p /hadoop/tmp /hadoop/namenode /hadoop/datanode /opt \
  && chown hadoop /hadoop /hadoop/* \
  && chmod 0750 /hadoop/*

COPY ./sw/hadoop-${hadoop_version}.tar.gz /opt/hadoop-${hadoop_version}.tar.gz
RUN tar zxf /opt/hadoop-${hadoop_version}.tar.gz -C /opt/ \
  && chown -R hadoop /opt/hadoop-${hadoop_version} \
  && ln -s /opt/hadoop-${hadoop_version} /opt/hadoop

COPY config/core-site.xml config/hdfs-site.xml config/yarn-site.xml config/mapred-site.xml config/hdfs-site.xml /opt/hadoop/etc/hadoop/

ENV PATH=/usr/lib/jvm/java-8-openjdk-amd64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/hadoop/bin/
ENV YARN_CONF_DIR=/opt/hadoop/etc/hadoop
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

USER hadoop
WORKDIR /home/hadoop
CMD echo
