FROM ubuntu:20.04

ARG hadoop_version='3.3.1'

RUN apt-get update
RUN apt-get install -y openjdk-8-jdk python3
RUN apt-get install -y sudo ssh wget nano vim git

RUN useradd -ms /bin/bash hadoop && echo "hadoop:supergroup" | chpasswd && adduser hadoop sudo && echo "hadoop     ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && cd /usr/bin/ && sudo ln -s python3 python

RUN mkdir -p /hadoop/tmp /hadoop/namenode /hadoop/datanode /opt \
  && chown hadoop /hadoop /hadoop/* \
  && chmod 0750 /hadoop/*

COPY ./sw/hadoop-${hadoop_version}.tar.gz /opt/hadoop-${hadoop_version}.tar.gz
RUN tar zxf /opt/hadoop-${hadoop_version}.tar.gz -C /opt/ \
  && chown -R hadoop /opt/hadoop-${hadoop_version} \
  && ln -s /opt/hadoop-${hadoop_version} /opt/hadoop \
  && rm /opt/hadoop-${hadoop_version}.tar.gz

ENV HADOOP_HOME=/opt/hadoop
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

COPY config/core-site.xml config/hdfs-site.xml config/yarn-site.xml config/mapred-site.xml config/hdfs-site.xml /opt/hadoop/etc/hadoop/

ENV PATH=${JAVA_HOME}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${HADOOP_HOME}/bin/
ENV YARN_CONF_DIR=${HADOOP_HOME}/etc/hadoop

USER hadoop
WORKDIR /home/hadoop
CMD echo
