FROM openjdk:8

ARG hadoop_version='3.2.0'
ARG spark_version='2.4.4'
ARG spark_hadoop_compat='2.7'

#ARG ubuntu_mirror='http://mirror.its.sfu.ca/mirror/ubuntu/'
#ARG ubuntu_security_mirror='http://mirror.its.sfu.ca/mirror/ubuntu/'
#ARG apache_mirror="http://mirror.csclub.uwaterloo.ca/apache/"

#RUN apt-get update \
#  && apt-get install -y nginx-module-geoip \
#  && apt-get clean \
#  && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash hadoop
#RUN mkdir /home/hadoop/.ssh && chown hadoop /home/hadoop/.ssh && chmod 0700 /home/hadoop/.ssh
#COPY config/id_rsa /home/hadoop/.ssh/id_rsa

RUN mkdir -p /hadoop/tmp /hadoop/namenode /hadoop/datanode /opt \
  && chown hadoop /hadoop /hadoop/* \
  && chmod 0750 /hadoop/*

COPY ./sw/hadoop-${hadoop_version}.tar.gz /opt/hadoop-${hadoop_version}.tar.gz
RUN tar zxf /opt/hadoop-${hadoop_version}.tar.gz -C /opt/ \
  && chown -R hadoop /opt/hadoop-${hadoop_version} \
  && ln -s /opt/hadoop-${hadoop_version} /opt/hadoop

COPY ./sw/spark-${spark_version}-bin-hadoop${spark_hadoop_compat}.tgz /opt/spark-${spark_version}-bin-hadoop${spark_hadoop_compat}.tgz
RUN tar zxf /opt/spark-${spark_version}-bin-hadoop${spark_hadoop_compat}.tgz -C /opt/ \
  && chown -R hadoop /opt/spark-${spark_version}-bin-hadoop${spark_hadoop_compat} \
  && ln -s /opt/spark-${spark_version}-bin-hadoop${spark_hadoop_compat} /opt/spark


